export const images = ["/Jewelry/1 of 1 Necklace.png",
"/Jewelry/Bok Choy Necklace.png",
"/Jewelry/Charmed Necklace.png",
"/Jewelry/Coquette Earrings.png",
"/Jewelry/Coquette Necklace.png",
"/Jewelry/Crying 4 U Earrings.png",
"/Jewelry/Evil Eye Earrings.png",
"/Jewelry/Metal Face Earrings.png",
"/Jewelry/Skulls and Dice Necklace.png",
"/Jewelry/Spicy Earrings.png",
"/Jewelry/Tony Necklace.png"];
